const companies = [
  {
    id: 1,
    logo: "https://via.placeholder.com/150",
    name: "PT Transportasi Umum",
    location: "Location F",
    industry: "Transportation",
    sub_industry: "Public Transport",
    company_category: "Kecil",
    sales_growth_projection: "35",
    credit_financing_needs: 5000000,
    total_assets: 50000000,
    average_annual_sales: 45000000,
    profit_or_loss: 2000000,
    competition_level: "Medium",
    dividend: 0.04,
    price: 300000000,
  },
  {
    id: 2,
    logo: "https://via.placeholder.com/150",
    name: "PT Teknologi Canggih",
    location: "Location A",
    industry: "Technology",
    sub_industry: "Software",
    company_category: "Menengah",
    sales_growth_projection: "50",
    credit_financing_needs: 10000000,
    total_assets: 100000000,
    average_annual_sales: 90000000,
    profit_or_loss: 5000000,
    competition_level: "High",
    dividend: 0.05,
    price: 500000000,
  },
  {
    id: 3,
    logo: "https://via.placeholder.com/150",
    name: "PT Pakaian Sejahtera",
    location: "Location B",
    industry: "Apparel",
    sub_industry: "Retail",
    company_category: "Kecil",
    sales_growth_projection: "20",
    credit_financing_needs: 3000000,
    total_assets: 20000000,
    average_annual_sales: 15000000,
    profit_or_loss: 1000000,
    competition_level: "Low",
    dividend: 0.03,
    price: 150000000,
  },
  {
    id: 4,
    logo: "https://via.placeholder.com/150",
    name: "PT Makanan Lezat",
    location: "Location C",
    industry: "Food & Beverage",
    sub_industry: "Restaurant",
    company_category: "Menengah",
    sales_growth_projection: "40",
    credit_financing_needs: 7000000,
    total_assets: 60000000,
    average_annual_sales: 55000000,
    profit_or_loss: 3000000,
    competition_level: "Medium",
    dividend: 0.04,
    price: 350000000,
  },
  {
    id: 5,
    logo: "https://via.placeholder.com/150",
    name: "PT Barang Mentah",
    location: "Location D",
    industry: "Raw Materials",
    sub_industry: "Mining",
    company_category: "Besar",
    sales_growth_projection: "60",
    credit_financing_needs: 20000000,
    total_assets: 200000000,
    average_annual_sales: 180000000,
    profit_or_loss: 10000000,
    competition_level: "High",
    dividend: 0.06,
    price: 800000000,
  },
];

export default function generateDummyCompanies() {
  return companies;
}

export function getDummyCompanyById(id) {
  return companies.find((company) => company.id === parseInt(id));
}
